### ISSUE TITLE
Responsive homepage

### ISSUE THREAD

**Issue by Johan-Mb** [WildCodeSchool/php_projet2_nantes_september2021_sherlock#17]
- Tout diminue en responsive, c'est cool, mais pas le bouton play qui parait très gros.
 - Le background-image est déformé en mode responsive
 - Les règles du jeu ne sont pas responsive 
 - Le footer non plus

**Comment by Lena-hub** [comment]
Ils n'avaient pas la version responsive a faire ..  :)
