### ISSUE TITLE
Fonction Suppr /adminQuestions

### ISSUE THREAD

**Issue by Johan-Mb** [WildCodeSchool/php_projet2_nantes_september2021_sherlock#25]
Message d'erreur lors du clic sur l'icône pour supprimer la question : SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`sherlock`.`reponse_question`, CONSTRAINT `reponse_question_ibfk_3` FOREIGN KEY (`question_id`) REFERENCES `question` (`id`))

**Comment by Hellnettles** [comment]
C'est pas admin/enigme plutot ?
