### ISSUE TITLE
Page scénario: UX navigation pourrait être optimisée

### ISSUE THREAD

**Issue by AliceBraye44** [WildCodeSchool/php_projet2_nantes_september2021_sherlock#26]
http://localhost:8000/sherlock/escenario

* choix de l'enigne : au vue du titre je m'attendais à des elements cliquables 
* on ne voit pas tout de suite où jouer (bouton play en bas à droite ) 
* la partie indice est vide

**Comment by Johan-Mb** [comment]
- Idée : rajouter une flèche qui indique où se trouve le bouton play ?
